// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6sokgeEPqn20lzrhNApoH9bN5DK1SsLI',
    appId: '1:1094682048749:web:65e27bc8835261ce54b4e4',
    messagingSenderId: '1094682048749',
    projectId: 'drive-ea',
    authDomain: 'drive-ea.firebaseapp.com',
    databaseURL: 'https://drive-ea-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ea.appspot.com',
    measurementId: 'G-5XTCJL3SNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWWeY-wQWC0DJMGhopUQDWqDevHv957cY',
    appId: '1:1094682048749:android:6ed6ee1c9e16390d54b4e4',
    messagingSenderId: '1094682048749',
    projectId: 'drive-ea',
    databaseURL: 'https://drive-ea-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbSTTsLjJ0bgqPanf9taxhyo7Jgta-UQ',
    appId: '1:1094682048749:ios:88e497db1a383c9454b4e4',
    messagingSenderId: '1094682048749',
    projectId: 'drive-ea',
    databaseURL: 'https://drive-ea-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ea.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACbSTTsLjJ0bgqPanf9taxhyo7Jgta-UQ',
    appId: '1:1094682048749:ios:88e497db1a383c9454b4e4',
    messagingSenderId: '1094682048749',
    projectId: 'drive-ea',
    databaseURL: 'https://drive-ea-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ea.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6sokgeEPqn20lzrhNApoH9bN5DK1SsLI',
    appId: '1:1094682048749:web:6546a28e3f02089354b4e4',
    messagingSenderId: '1094682048749',
    projectId: 'drive-ea',
    authDomain: 'drive-ea.firebaseapp.com',
    databaseURL: 'https://drive-ea-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ea.appspot.com',
    measurementId: 'G-D7LPSP92FE',
  );
}
